import { ProjectHero } from "../components/ProjectHero";
import { ojcsProject } from "../data/projects";
import { usePageMetadata } from "../hooks/usePageMetadata";
import { PublicProjectLayout } from "../layouts/PublicProjectLayout";

export default function OJCSPage() {
  usePageMetadata(ojcsProject.seo);
  return <PublicProjectLayout><div className="ojcs-page">
    <ProjectHero project={ojcsProject} kicker="Application de repérage et de connexion utile" />
    <section className="project-section ojcs-section ojcs-problem" aria-labelledby="why-ojcs"><div><p className="section-kicker">Pourquoi OJCS</p><h2 id="why-ojcs">Retrouver des repères dans une information dispersée</h2></div><div><p className="project-section__lead">{ojcsProject.summary}</p><ul><li>Identifier les acteurs pertinents.</li><li>Comprendre où ils se trouvent.</li><li>Distinguer une information claire d’une promesse non qualifiée.</li></ul></div></section>
    <section className="ojcs-connect" aria-labelledby="connect-axes"><p className="section-kicker">Le parcours OJCS</p><h2 id="connect-axes">Explorer. Localiser. Qualifier. Contacter.</h2><p className="ojcs-connect__intro">Quatre axes pour organiser la circulation de l’information — pas quatre services déjà ouverts.</p><ol className="ojcs-axis-grid">{ojcsProject.connectAxes.map((x,i)=><li key={x.title}><span aria-hidden="true">0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></li>)}</ol></section>
    <section className="project-section ojcs-section ojcs-audiences" aria-labelledby="ojcs-publics"><div><p className="section-kicker">Pour qui</p><h2 id="ojcs-publics">Relier le terrain sans fabriquer un réseau social</h2><p>OJCS part de quatre groupes déjà identifiés, avec des usages qui restent à qualifier.</p></div><dl>{ojcsProject.audienceDetails.map(x=><div key={x.title}><dt>{x.title}</dt><dd>{x.description}</dd></div>)}</dl></section>
    <section className="project-section ojcs-section ojcs-current" aria-labelledby="ojcs-current"><p className="section-kicker">Ce qui existe aujourd’hui</p><h2 id="ojcs-current">Des fondations réelles, pas un service public ouvert</h2><div className="ojcs-current-grid">{ojcsProject.currentCapabilities.map((x,i)=><article key={x.title}><span aria-hidden="true">0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>
    <section className="project-section ojcs-section ojcs-building" aria-labelledby="ojcs-planned"><div><p className="section-kicker">Ce que nous construisons</p><h2 id="ojcs-planned">Quatre domaines à qualifier ensemble</h2></div><div className="ojcs-planned-grid">{ojcsProject.plannedCapabilities.map(x=><article key={x.title}><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>
    <section className="ojcs-territory" aria-labelledby="ojcs-geography"><div><p className="section-kicker">Guinée et diaspora</p><h2 id="ojcs-geography">La Guinée comme ancrage, la diaspora comme lien</h2><p>{ojcsProject.geography}</p></div><div className="ojcs-trust"><p className="section-kicker">Confiance</p><h3>Qualifier avant d’affirmer</h3><p>{ojcsProject.trustPrinciple}</p></div></section>
    <section className="project-section ojcs-section ojcs-trajectory" aria-labelledby="ojcs-roadmap"><div><p className="section-kicker">Trajectoire OJCS</p><h2 id="ojcs-roadmap">Étendre les connexions avec maîtrise</h2><p>{ojcsProject.vision}</p></div><ol>{ojcsProject.roadmap.map((x,i)=><li key={x.label}><span aria-hidden="true">0{i+1}</span><h3>{x.label}</h3><p>{x.description}</p></li>)}</ol></section>
    <section className="project-final-cta ojcs-final-cta" aria-labelledby="ojcs-cta"><div><p className="section-kicker">Dans OnJarama</p><h2 id="ojcs-cta">Une application en construction, reliée à un écosystème public</h2><p>OJW présente le projet ; OJF en porte le cadre institutionnel. OJCS reste une application en développement, sans service public ouvert.</p></div><div className="project-final-cta__actions"><a className="button button-primary" href={ojcsProject.primaryAction.href}>{ojcsProject.primaryAction.label}</a><a className="button button-secondary" href={ojcsProject.secondaryAction.href}>{ojcsProject.secondaryAction.label}</a></div></section>
  </div></PublicProjectLayout>;
}
