import { ProjectHero } from "../components/ProjectHero";
import { ProjectStatus } from "../components/ProjectStatus";
import { ojcsProject } from "../data/projects";
import { usePageMetadata } from "../hooks/usePageMetadata";
import { PublicProjectLayout } from "../layouts/PublicProjectLayout";

const publicRoadmapStage = { CURRENT: "En cours de structuration", PLANNED: "À construire", VISION: "Vision" } as const;

export default function OJCSPage() {
  usePageMetadata(ojcsProject.seo);
  return <PublicProjectLayout><div className="ojcs-page">
    <ProjectHero project={ojcsProject} kicker="OnJarama Connect Services" />
    <section className="project-section ojcs-section" aria-labelledby="why-ojcs"><p className="section-kicker">Pourquoi OJCS</p><h2 id="why-ojcs">Rendre les connexions utiles plus simples</h2><p className="project-section__lead">{ojcsProject.summary}</p><p>OJCS cherche à rendre plus visibles des services et ressources utiles, à réduire la dispersion de l’information et à faciliter progressivement des connexions pertinentes, sans présenter ces services comme déjà publics.</p></section>
    <section className="project-section ojcs-section ojcs-connect" aria-labelledby="connect-axes"><p className="section-kicker">La direction produit</p><h2 id="connect-axes">Explorer. Localiser. Qualifier. Contacter.</h2><div className="ojcs-axis-grid">{ojcsProject.connectAxes.map((x,i)=><article key={x.title}><span aria-hidden="true">0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>
    <section className="project-section ojcs-section" aria-labelledby="ojcs-publics"><p className="section-kicker">Pour qui</p><h2 id="ojcs-publics">Quatre familles, des usages à qualifier</h2><div className="ojcs-audience-grid">{ojcsProject.audienceDetails.map(x=><article key={x.title}><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>
    <section className="project-section ojcs-section ojcs-current" aria-labelledby="ojcs-current"><p className="section-kicker">État du développement</p><h2 id="ojcs-current">Ce qui est déjà engagé</h2><div className="project-capabilities ojcs-current-grid">{ojcsProject.currentCapabilities.map(x=><article key={x.title}><ProjectStatus label="Ce qui est déjà engagé" stage={x.stage}/><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>
    <section className="project-section ojcs-section ojcs-building" aria-labelledby="ojcs-planned"><p className="section-kicker">En construction</p><h2 id="ojcs-planned">Ce que nous construisons</h2><div className="ojcs-planned-grid">{ojcsProject.plannedCapabilities.map(x=><article key={x.title}><ProjectStatus label="À construire" stage={x.stage}/><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>
    <section className="ojcs-geography" aria-labelledby="ojcs-geography"><ProjectStatus label="Direction géographique" stage="PLANNED"/><p className="section-kicker">Guinée d’abord</p><h2 id="ojcs-geography">Du terrain vers des connexions plus utiles</h2><p>{ojcsProject.geography}</p></section>
    <section className="ojcs-trust" aria-labelledby="ojcs-trust"><div><p className="section-kicker">Connexion responsable</p><h2 id="ojcs-trust">La confiance se construit avant de s’affirmer</h2></div><p>{ojcsProject.trustPrinciple}</p></section>
    <section className="ojcs-vision" aria-labelledby="ojcs-vision"><ProjectStatus label="Vision" stage="VISION"/><p className="section-kicker">Trajectoire</p><h2 id="ojcs-vision">Voir ce qui existe. Trouver ce qui correspond. Se connecter utilement.</h2><p>{ojcsProject.vision}</p></section>
    <section className="project-section ojcs-section" aria-labelledby="ojcs-roadmap"><p className="section-kicker">Trajectoire OJCS</p><h2 id="ojcs-roadmap">Cinq phases publiques, sans date artificielle</h2><ol className="project-roadmap ojcs-roadmap">{ojcsProject.roadmap.map(x=><li key={x.label}><ProjectStatus label={publicRoadmapStage[x.stage]} stage={x.stage}/><h3>{x.label}</h3><p>{x.description}</p></li>)}</ol></section>
    <section className="project-section ojcs-section" aria-labelledby="ojcs-ecosystem"><p className="section-kicker">Dans l’écosystème OnJarama</p><h2 id="ojcs-ecosystem">Le pôle de connexion et de services utiles</h2><div className="project-relations ojcs-relations"><article><h3>OJCS</h3><p>OJCS est le pôle de connexion et de services utiles de l’écosystème.</p></article>{ojcsProject.ecosystemRole.projects.map(x=><article key={x.shortName}><h3>{x.shortName}</h3><p>{x.relation}</p></article>)}<article className="project-relations__foundation"><h3>OJF — Fondation</h3><p>{ojcsProject.ecosystemRole.foundation.relation}</p></article></div></section>
    <section className="project-final-cta ojcs-final-cta" aria-labelledby="ojcs-cta"><div><p className="section-kicker">Continuer</p><h2 id="ojcs-cta">Découvrir l’écosystème et sa trajectoire</h2></div><div className="project-final-cta__actions"><a className="button button-primary" href={ojcsProject.primaryAction.href}>{ojcsProject.primaryAction.label}</a><a className="button button-secondary" href={ojcsProject.secondaryAction.href}>{ojcsProject.secondaryAction.label}</a></div></section>
  </div></PublicProjectLayout>;
}
