import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const doc = readFileSync("docs/OJW-LIVING-ENVIRONMENT-LE-05-AUTO-CELESTIAL-PRE1.md", "utf8");
const clock = readFileSync("src/hooks/useEnvironmentClock.ts", "utf8");
const mode = readFileSync("src/hooks/useDayNightMode.ts", "utf8");
const environment = readFileSync("src/hooks/useLivingEnvironment.ts", "utf8");
const solar = readFileSync("src/utils/solarDayNight.ts", "utf8");
const sky = readFileSync("src/utils/dynamicSky.ts", "utf8");
const scene = readFileSync("src/components/TreeScene.tsx", "utf8");
const location = readFileSync("src/hooks/useLocalCelestialLocation.ts", "utf8");
const locationControl = readFileSync("src/components/LocalSkyControl.tsx", "utf8");
const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const runtime = `${clock}\n${mode}\n${environment}\n${solar}\n${sky}\n${scene}\n${location}\n${locationControl}`;

assert.match(doc, /AUTO_CURRENT = ARTISTIC_TIME_BASED/);
assert.match(doc, /LOCATION_TRANSMISSION = NONE/);
assert.match(doc, /LOCATION_PRECISION = 0\.25_DEGREE/);
assert.match(doc, /LOCATION_PERMISSION_TRIGGER = EXPLICIT_USER_ACTION_ONLY/);
assert.match(doc, /LOCATION_FALLBACK = ARTISTIC_TIME_BASED_CURRENT_MODEL/);
assert.match(doc, /LOCATION_STORAGE = LOCAL_ONLY_COARSE_COORDINATES/);
assert.match(doc, /RAW_COORDINATE_STORAGE = FORBIDDEN/);
assert.match(doc, /LOCATION_CLEAR_CONTROL = REQUIRED/);
assert.match(doc, /LOCATION_WATCH = OFF/);
assert.match(doc, /MANUAL_CITY_SELECTION_V1 = DEFERRED/);
assert.match(doc, /ASTRONOMY_ENGINE = SUNCALC_2_0_1_APPROVED/);
assert.match(doc, /ASTRONOMY_ENGINE_TARGET_PACKAGE = suncalc@2\.0\.1/);
assert.match(doc, /ASTRONOMY_EXECUTION = LOCAL_ONLY/);
assert.match(doc, /RUNTIME_IMPLEMENTATION = AUTHORIZED_FOR_NEXT_GATE_ONLY/);
assert.match(doc, /MANUAL_DAY_MODE = ARTISTIC_DETERMINISTIC/);
assert.match(doc, /MANUAL_NIGHT_MODE = ARTISTIC_DETERMINISTIC/);
assert.match(doc, /CELESTIAL_UPDATE_SOURCE = USE_ENVIRONMENT_CLOCK/);
assert.match(doc, /BELOW_HORIZON_SOURCE_VISIBLE = FALSE/);
assert.match(doc, /AUTO_LOCAL_DAY_THRESHOLD = SUN_ALTITUDE_GREATER_THAN_MINUS_6_DEGREES/);
assert.match(doc, /AUTO_LOCAL_NIGHT_THRESHOLD = SUN_ALTITUDE_LESS_OR_EQUAL_MINUS_6_DEGREES/);
assert.match(doc, /AUTO_LOCAL_SUN_MOON_VISIBILITY = INDEPENDENT/);
assert.match(doc, /AUTO_LOCAL_DUAL_ASTRES = ALLOWED_WHEN_ASTRONOMICALLY_VISIBLE/);
assert.match(doc, /ASTRE_BELOW_HORIZON = HIDDEN/);
assert.match(doc, /ASTRE_OUTSIDE_HERO_FOV = HIDDEN/);
assert.match(doc, /HERO_VIRTUAL_CAMERA_HEADING = EQUATOR_FACING/);
assert.match(doc, /HERO_HORIZONTAL_FOV = 180_DEGREES/);
assert.match(doc, /MOON_SIZE_DESKTOP = 28PX/);
assert.match(doc, /MOON_SIZE_MOBILE = 20PX/);
assert.match(doc, /MOON_DISTANCE_SIZE_VARIATION = STRONGLY_LIMITED/);
assert.match(doc, /MOON_PHASE = ASTRONOMICAL/);
assert.match(doc, /MOON_ORIENTATION = BRIGHT_LIMB_ANGLE_MINUS_PARALLACTIC_ANGLE/);
assert.match(doc, /ASTRONOMICAL_REFRESH = SHARED_MINUTE_CLOCK_PLUS_BROWSER_REENTRY_EVENTS/);
assert.match(doc, /REAL_WEATHER = OFF/);

assert.match(clock, /60_000/);
assert.match(clock, /visibilitychange/);
assert.match(mode, /resolveFallbackDayNightMode/);
assert.match(environment, /useEnvironmentClock/);
assert.match(environment, /useDayNightMode/);
assert.match(environment, /resolveInternalDynamicSky/);
assert.match(solar, /resolveLocalCelestialState/);
assert.match(sky, /resolveMoonPhase/);
assert.match(locationControl, /Autoriser la localisation/);
assert.match(location, /navigator\.geolocation\.getCurrentPosition/);
assert.doesNotMatch(runtime, /watchPosition|fetch\(|XMLHttpRequest|sendBeacon|WebSocket/i);
assert.equal(pkg.dependencies.suncalc, "2.0.1");
assert.equal(pkg.dependencies["astronomy-engine"], undefined);

console.log("OJW-LIVING-ENVIRONMENT-LE-05-PRE1: approved local astronomical decisions remain locked through implementation.");
